version: '3.8'

services:
  db:
    container_name: kaamgar
    image: postgis/postgis:latest # ✅ Switch to PostGIS image
    restart: always
    ports:
      - "2010:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data_kaamgar:/var/lib/postgresql/data
volumes:
  db_data_kaamgar:
